POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0ZjRjZmU1MzYxOWVjN2U2NWY3ZjUyMCIsImlhdCI6MTY5MzgxNjk4Mn0.qMDE7GaG7bd22uIZsYS2L1dPLlWa-kJCjS5C-KrYkuY

{
    "content": "auth tokens are awesome",
    "important": true
}